version: '3'


services:
  php:
    build:
      context: .
    environment:
      REDIS_HOST: redis
      DB_HOST: db
    volumes:
      - ./:/var/www/html

  web:
    image: nginx
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - .docker/nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80

  node:
    image: node:14
    user: node
    working_dir: /assets
    ports:
      - 5173:5173
    volumes:
      - ./:/assets
    command: npm run dev

  db:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      # MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_DATABASE}"
    volumes:
      - mysqldata:/var/lib/mysql

  # redis:
  #   image: redis:5
  #   volumes:
  #     - redisdata:/data

volumes:
  mysqldata:
  # redisdata:
